Async functions to await a full or empty queue
bikeshedder/deadqueue pull request #4
Opened 2022-03-11 16:26 UTC by overhacked

Allow awaiting a full or empty queue.

- `Queue.empty()` is useful for chaining futures
  in a multi-threaded program when some subsequent
  action, like a verification step, needs to be
  taken once the queue is emptied.
- `Queue.full()` can help manage backpressure so that
  an autoscaling system can monitor when the queue fills
  before it starts increasing the number of workers.

2022-03-18 13:52 UTC, bikeshedder requested changes
This is a nice addition to the crate.

I just think the "simple" implementations of those methods using just `Semaphore::acquire_many` are wrong. I'd like to see a test case that actually checks if calling the `full` and `empty` method don't block concurrent `push` and `pop` calls. The tests would look like that:
- Full
   - Create a queue with capacity of 2
   - call `full`  (`tokio::spawn`)
   - call `push`
   - call `pop` and make sure it doesn't block
   - call `push` twice and check that the `full` call returned
- Empty
    - Create a queue with capacity of 2
    - call `push` twice
    - call `empty` (`tokio::spawn`)
    - call `push`
    - call `pop` and make sure it doesn't block
    - call `pop` twice and check that `empty` call returned

One more thing: I don't like the names `empty` and `full`. `empty` almost sounds like it is supposed to `clear` the queue. How about creating naming them `wait_empty`/`wait_full` or `on_empty`/`on_full` instead? That would make it very clear that the queues aren't modified but you're waiting for a specific event to happen.

2022-03-18 13:52 UTC, bikeshedder commented on src/limited.rs
> +        let _ = self.pop_semaphore.acquire_many(capacity).await.unwrap();
Tokio semaphores are fair in nature. This `acquire_many` call will actually block all other `acquire` calls until the queue is full. If you were to call this on a queue and you never put in `capacity` objects this call never returns and other calls to `pop` will be blocked indefinitely.

2022-03-18 13:52 UTC, bikeshedder commented on src/limited.rs
> +        let _ = self.push_semaphore.acquire_many(capacity).await.unwrap();
This `acquire_many` call has the same problem as in the `full()` method.

2022-03-18 13:52 UTC, bikeshedder commented on src/resizable.rs
> +            let _permit = self.push_semaphore.acquire_many(capacity).await.unwrap();
Just like in the `limited` implementation I don't think this is correct. I guess the only (and correct) way around it is to use a channel for both `full` and `empty` notifications.

2022-03-18 14:02 UTC, bikeshedder commented
If you were to change the `deadqueue::atomic::Available` implementation so it returns the new (or old) value after `add` and `sub` you could use that to find out if the queue is full and/or empty. That way you could avoid calling `available_permits` and remove one possible race condition where the queue is empty for the fraction of a second but `Semaphore::available_permits` doesn't show that because of concurrent `push`/`pop` calls.

Even then you might miss an `empty`/`full` event, but it's less likely to happen than calling into `Semaphore::available_permits` outside of any atomic guarantees.

2022-03-22 15:03 UTC, overhacked commented
Hi, read all these comments. Thanks for the feedback! Trying to find time to rework the PR accordingly.

2023-07-28 17:44 UTC, overhacked commented
Finally circled back to this and updated the `wait_full()` and `wait_empty()` to use atomics instead of `Semaphore::available_permits()`. Thanks for your patience and not closing the PR.

2023-11-09 12:17 UTC, bikeshedder commented
Sorry for taking so long. I completely forgot about that PR. :see_no_evil: 

After reviewing it I only found two small details:

1. Every time you use `Available:add` you add 1 to the previous value to see if the capacity has been reached. I'd rather change that code so the `Available:add` function already returns the new value so this comparison doesn't need to happen. The same can be done for `Available::sub` where comparing the new value against `0` is much clearer than comparing the previous value against `1`.

2. It would be nice if there was a way to get a hold of the watch channel of `full` and `empty`. That way an application that wants to perform some task every time the queue is full or empty doesn't need to continuously recreate the channel receiver.

If you happen to find time to look into that I'll wait a bit. I'm just as happy to merge this PR without those changes.

2023-11-09 12:20 UTC, bikeshedder commented on src/resizable.rs
> +                // Currently this is a no-op because this resize() function
What do you mean by that? `resize()` takes a `&self` not a `&mut self`. :thinking:

2023-11-09 12:22 UTC, bikeshedder commented
Oh, and please explain this comment to me...
- https://github.com/bikeshedder/deadqueue/pull/4/files#r1387924883

How is it borrowed mutably? :thinking:

2023-11-09 21:58 UTC, overhacked commented
I should be able to look at these this weekend. Thanks!On Nov 9, 2023, at 7:18 AM, Michael P. Jung ***@***.***> wrote:﻿
Sorry for taking so long. I completely forgot about that PR. 🙈
After reviewing it I only found two small details:


Every time you use Available:add you add 1 to the previous value to see if the capacity has been reached. I'd rather change that code so the Available:add function already returns the new value so this comparison doesn't need to happen. The same can be done for Available::sub where comparing the new value against 0 is much clearer than comparing the previous value against 1.


It would be nice if there was a way to get a hold of the watch channel of full and empty. That way an application that wants to perform some task every time the queue is full or empty doesn't need to continuously recreate the channel receiver.


If you happen to find time to look into that I'll wait a bit. I'm just as happy to merge this PR without those changes.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-01-08 09:56 UTC, bikeshedder commented
@overhacked Any updates on this PR?

2024-01-09 17:19 UTC, overhacked commented
Requested changes pushed. Sorry I lost track of wrapping this up in the last few months of the year. Nothing going on in November or December... nothing else at all. :wink:

Thanks for your patience and support with this!

2024-01-10 14:10 UTC, bikeshedder approved these changes

2024-01-10 14:10 UTC, merged

2024-01-10 14:10 UTC, bikeshedder commented
Thanks a lot. Awesome work! :tada:

2025-07-16 15:45 UTC, bikeshedder commented
I just saw that I never actually released a new version including your changes. :facepalm: 

I just releated `deadqueue 0.2.5` on crates.io:

:package: https://crates.io/crates/deadqueue/0.2.5

Thanks again for this PR! :heart:

2025-07-16 16:57 UTC, overhacked commented
Amazing, thank you!